/**
 * Builds three things:
 *
 *   dist/nishachar-ide.js       ESM, for bundlers and <script type="module">
 *   dist/nishachar-ide.iife.js  classic script, for a plain <script> tag
 *   ../core/nishachar/static/   the standalone IDE, served by `nishachar`
 *
 * It also generates src/generated/languages.js from the registry at the repo
 * root, so the component ships the language list without needing a backend and
 * the registry stays the single source of truth.
 */

import { build, context } from 'esbuild';
import { readFile, readdir, writeFile, mkdir, cp } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../..');
const LANGUAGES = join(ROOT, 'languages');
const GENERATED = join(HERE, 'src/generated');
const STATIC = resolve(ROOT, 'packages/core/nishachar/static');

const watch = process.argv.includes('--watch');

/** Inline the registry so the component works with no network and no backend. */
async function generateLanguages() {
  const files = (await readdir(LANGUAGES)).filter(
    (name) => name.endsWith('.json') && name !== 'schema.json'
  );

  const languages = [];
  for (const name of files) {
    const raw = JSON.parse(await readFile(join(LANGUAGES, name), 'utf8'));
    languages.push({
      id: raw.id,
      name: raw.name,
      aliases: raw.aliases ?? [],
      extensions: raw.extensions ?? [],
      comment: raw.comment ?? '#',
      highlight: raw.highlight ?? 'text',
      template: raw.template ?? '',
      website: raw.website ?? '',
      browser: raw.browser ?? '',
      compiled: Boolean(raw.compile),
    });
  }
  languages.sort((a, b) => a.name.localeCompare(b.name, 'en', { sensitivity: 'base' }));

  const version = JSON.parse(await readFile(join(HERE, 'package.json'), 'utf8')).version;
  await mkdir(GENERATED, { recursive: true });
  await writeFile(
    join(GENERATED, 'languages.js'),
    `// Generated by build.mjs from languages/*.json -- do not edit by hand.\n` +
      `export const VERSION = ${JSON.stringify(version)};\n` +
      `export const LANGUAGES = ${JSON.stringify(languages, null, 0)};\n`,
    'utf8'
  );
  console.log(`  registry   ${languages.length} languages ` +
    `(${languages.filter((l) => l.browser).length} run in-browser)`);
  return languages;
}

const shared = {
  bundle: true,
  minify: !watch,
  sourcemap: true,
  target: ['es2022', 'chrome100', 'firefox100', 'safari15'],
  legalComments: 'none',
  logLevel: 'warning',
  banner: {
    js: '/*! ni_sh_a.char-IDE -- Apache-2.0 -- https://github.com/ni-sh-a-char/ni_sh_a.char-IDE */',
  },
};

const targets = [
  { entryPoints: [join(HERE, 'src/index.js')], outfile: join(HERE, 'dist/nishachar-ide.js'), format: 'esm' },
  { entryPoints: [join(HERE, 'src/index.js')], outfile: join(HERE, 'dist/nishachar-ide.iife.js'), format: 'iife', globalName: 'NishacharIDE' },
  { entryPoints: [join(HERE, 'src/shell/app.js')], outfile: join(STATIC, 'app.js'), format: 'esm' },
];

async function buildAll() {
  await generateLanguages();

  if (watch) {
    for (const target of targets) {
      const ctx = await context({ ...shared, ...target });
      await ctx.watch();
    }
    console.log('  watching for changes…');
    return;
  }

  await Promise.all(targets.map((target) => build({ ...shared, ...target })));

  await mkdir(STATIC, { recursive: true });
  await cp(join(HERE, 'src/shell/index.html'), join(STATIC, 'index.html'));

  for (const target of targets) {
    if (existsSync(target.outfile)) {
      const size = (await readFile(target.outfile)).length;
      const label = target.outfile.replace(ROOT, '.').replace(/\\/g, '/');
      console.log(`  ${label}  ${(size / 1024).toFixed(1)} kB`);
    }
  }
}

buildAll().catch((error) => {
  console.error(error);
  process.exit(1);
});
