#!/usr/bin/env python3
"""Generate the language registry for the Dart and Kotlin clients.

`languages/*.json` is the single source of truth. The JavaScript component
inlines it at bundle time (see packages/web/build.mjs), but Dart and Kotlin
publish source to their registries, so their copies have to be committed.

Run this after changing anything in `languages/`:

    python tools/generate_bindings.py

CI runs it with --check and fails if the committed output has drifted.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = ROOT / "languages"

DART_OUT = ROOT / "packages/dart/lib/src/registry.g.dart"
KOTLIN_OUT = ROOT / "packages/kotlin/src/main/kotlin/io/github/nishachar/Registry.kt"

BANNER = "Generated by tools/generate_bindings.py from languages/*.json. Do not edit."


def load() -> list[dict]:
    entries = []
    for path in sorted(LANGUAGES.glob("*.json")):
        if path.name == "schema.json":
            continue
        raw = json.loads(path.read_text(encoding="utf-8"))
        entries.append(
            {
                "id": raw["id"],
                "name": raw["name"],
                "aliases": raw.get("aliases", []),
                "extensions": raw["extensions"],
                "comment": raw.get("comment", "#"),
                "highlight": raw.get("highlight", "text"),
                "template": raw.get("template", ""),
                "website": raw.get("website", ""),
                "browser": raw.get("browser", ""),
                "compiled": bool(raw.get("compile")),
            }
        )
    entries.sort(key=lambda e: e["name"].lower())
    return entries


def dart_string(value: str) -> str:
    """A Dart single-quoted literal. Dart interpolates $, so escape it too."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("$", "\\$")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f"'{escaped}'"


def dart_list(values: list[str]) -> str:
    return "[" + ", ".join(dart_string(v) for v in values) + "]"


def render_dart(entries: list[dict]) -> str:
    lines = [
        f"// {BANNER}",
        "",
        "// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars",
        "",
        "import 'language.dart';",
        "",
        "/// Every language the IDE knows about, sorted by display name.",
        "const List<Language> kLanguages = <Language>[",
    ]
    for entry in entries:
        lines += [
            "  Language(",
            f"    id: {dart_string(entry['id'])},",
            f"    name: {dart_string(entry['name'])},",
            f"    aliases: {dart_list(entry['aliases'])},",
            f"    extensions: {dart_list(entry['extensions'])},",
            f"    comment: {dart_string(entry['comment'])},",
            f"    highlight: {dart_string(entry['highlight'])},",
            f"    template: {dart_string(entry['template'])},",
            f"    website: {dart_string(entry['website'])},",
            f"    browser: {dart_string(entry['browser'])},",
            f"    compiled: {str(entry['compiled']).lower()},",
            "  ),",
        ]
    lines += ["];", ""]
    return "\n".join(lines)


def kotlin_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def kotlin_list(values: list[str]) -> str:
    if not values:
        return "emptyList()"
    return "listOf(" + ", ".join(kotlin_string(v) for v in values) + ")"


def render_kotlin(entries: list[dict]) -> str:
    lines = [
        f"// {BANNER}",
        "",
        "package io.github.nishachar",
        "",
        "/** Every language the IDE knows about, sorted by display name. */",
        "public val LANGUAGES: List<Language> = listOf(",
    ]
    for entry in entries:
        lines += [
            "    Language(",
            f"        id = {kotlin_string(entry['id'])},",
            f"        name = {kotlin_string(entry['name'])},",
            f"        aliases = {kotlin_list(entry['aliases'])},",
            f"        extensions = {kotlin_list(entry['extensions'])},",
            f"        comment = {kotlin_string(entry['comment'])},",
            f"        highlight = {kotlin_string(entry['highlight'])},",
            f"        template = {kotlin_string(entry['template'])},",
            f"        website = {kotlin_string(entry['website'])},",
            f"        browser = {kotlin_string(entry['browser'])},",
            f"        compiled = {str(entry['compiled']).lower()},",
            "    ),",
        ]
    lines += [")", ""]
    return "\n".join(lines)


def _dart_format(source: str) -> str:
    """Return `source` as `dart format` would write it.

    Without this the generated file changes the next time anyone formats the
    package, and the drift check fails on output nobody actually edited. When
    the Dart SDK is not installed the source is returned unchanged, so the
    generator still works -- the drift check runs in a job that has Dart.
    """
    import shutil
    import subprocess
    import tempfile

    dart = shutil.which("dart")
    if dart is None:
        return source

    with tempfile.TemporaryDirectory(prefix="nishachar-fmt-") as scratch:
        scratchpad = Path(scratch, "registry.g.dart")
        scratchpad.write_text(source, encoding="utf-8")
        done = subprocess.run(
            [dart, "format", str(scratchpad)], capture_output=True, check=False
        )
        if done.returncode != 0:
            return source
        return scratchpad.read_text(encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed output differs, instead of rewriting it",
    )
    args = parser.parse_args()

    entries = load()
    outputs = {
        DART_OUT: _dart_format(render_dart(entries)),
        KOTLIN_OUT: render_kotlin(entries),
    }

    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    if stale:
        for path in stale:
            rel = path.relative_to(ROOT)
            print(f"::error file={rel}::out of date -- run: python tools/generate_bindings.py")
        return 1

    print(f"{len(entries)} languages; bindings up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
